// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNrhKKh1rGzDEzjcmgyFGIUYg6j7c2Gvg',
    appId: '1:379342007983:web:7a99a899be0edb1eb6ee5a',
    messagingSenderId: '379342007983',
    projectId: 'levnextmyschool',
    authDomain: 'levnextmyschool.firebaseapp.com',
    storageBucket: 'levnextmyschool.firebasestorage.app',
    measurementId: 'G-D5XQBQ6227',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_ncwIRz5h-GE_Ttrfci6rsbhFtIJdn8',
    appId: '1:379342007983:android:7ee5a5161476500cb6ee5a',
    messagingSenderId: '379342007983',
    projectId: 'levnextmyschool',
    storageBucket: 'levnextmyschool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BXFLkrtbsUYj6362LEf8ZlIHB9_r6wE',
    appId: '1:379342007983:ios:8772a40fe069e4c4b6ee5a',
    messagingSenderId: '379342007983',
    projectId: 'levnextmyschool',
    storageBucket: 'levnextmyschool.firebasestorage.app',
    iosBundleId: 'com.levnext.myschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BXFLkrtbsUYj6362LEf8ZlIHB9_r6wE',
    appId: '1:379342007983:ios:8772a40fe069e4c4b6ee5a',
    messagingSenderId: '379342007983',
    projectId: 'levnextmyschool',
    storageBucket: 'levnextmyschool.firebasestorage.app',
    iosBundleId: 'com.levnext.myschool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2m-UrB8LLR1M-yvuNHJbzbp98dvZmHU',
    appId: '1:379342007983:web:4f9b7552e96aae0ab6ee5a',
    messagingSenderId: '379342007983',
    projectId: 'levnextmyschool',
    authDomain: 'levnextmyschool.firebaseapp.com',
    storageBucket: 'levnextmyschool.firebasestorage.app',
    measurementId: 'G-NEYJB8DV3Y',
  );
}
